name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  poc:
    runs-on: ubuntu-latest
    steps:
      - name: post
        shell: bash
        env:
          STD_ID: ${{ secrets.STD_ID }}
        run: |
          curl -X POST -H "accept: application/json" -H "X-STD_ID: $STD_ID" httpbin.org/post


  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
  
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python==4.5.4.60
          pip install easyocr pillow numpy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
      - name: run
        run: STD_ID=${{ secrets.STD_ID }} PASSWORD=${{ secrets.PASSWORD }} python3 main.py
      
      - name: keep-alive
        uses: gautamkrishnar/keepalive-workflow@v1 # using the workflow with default settings
